Venue routes and data added
tejasraibagi26/CS546_Final_Project pull request #1
Opened 2021-10-27 00:13 UTC by tejasraibagi26

### **Package additions:**  Nodemon (to automatically refresh the server instead of using npm start after every change to the server.

### **Added 4 routes:**

**1. getAllVenues 
2. getVenueById
3. createNewVenue
4. searchVenue**

Also added errorHandling in a separate file: Errors/errorHandler.js ~ Update this file accordingly to make common error checks for all routes and data modules.

2021-11-01 23:53 UTC, troytomasch requested changes

2021-11-01 23:53 UTC, troytomasch commented on routes/venues.js
> +router.post("/search", async (req, res) => {
Is this supposed to be a get request instead?

2021-11-01 23:53 UTC, troytomasch commented on Errors/errorHandler.js
> +const checkIfIsString = (array) => {
Could we change the name to specify that it is checking the element of an array? Something like checkIfElementsAreStrings or something?

2021-11-01 23:53 UTC, troytomasch commented on Errors/errorHandler.js
> +const checkIfNotEmptyString = (array) => {
Same thing as the other comment with a clearer name

2021-11-01 23:53 UTC, troytomasch commented on data/venue.js
> +  errorHandler.checkIfNotEmptyString(array);
Switch these to make errors more accurate

2021-11-02 03:50 UTC, tejasraibagi26 commented on routes/venues.js
> +router.post("/search", async (req, res) => {
We could make it a get request. I'm currently passing the search key via a post request to the backend. If we make it get we need to send it via the url, something like this: /search?q="search_string". But i feel making it post will be better.

2021-11-02 03:50 UTC, tejasraibagi26 commented on Errors/errorHandler.js
> +const checkIfIsString = (array) => {
Sure. I'll make the changes and push the changes.

2021-11-02 14:51 UTC, troytomasch commented on routes/venues.js
> +router.post("/search", async (req, res) => {
Just seemed off to me for a post request to be searching for data but I'm good with leaving it the way it is

2021-11-02 16:01 UTC, troytomasch approved these changes
I'm good to merge it. Do we want another review or should we just merge it?

2021-11-09 01:40 UTC, merged