Tejas dev
tejasraibagi26/CS546_Final_Project pull request #10
Opened 2021-12-01 00:06 UTC by tejasraibagi26

Added booking, activity feed, game requests, client side checking.

2021-12-02 03:04 UTC, troytomasch requested changes
Just a couple minor changes. You're missing the require xss in a couple places as well as you left in a couple print statements. Also, one place that probably should get the id of the current user rather than be a constant id.

2021-12-02 04:07 UTC, tejasraibagi26 commented on data/activity.js
> +  let createdBy = "617310bd50b4d0d56abef917";
Yes. This is just a placeholder as we didn't have sessions. I'll do the changes.

2021-12-02 04:09 UTC, tejasraibagi26 commented on routes/bookings.js
> +const booking = data.booking;
Ahh yes good catch. Will add.

2021-12-02 04:10 UTC, tejasraibagi26 commented
> Just a couple minor changes. You're missing the require xss in a couple places as well as you left in a couple print statements. Also, one place that probably should get the id of the current user rather than be a constant id. 

I'll go ahead and commit the changes by tomorrow afternoon.

2021-12-02 17:14 UTC, tejasraibagi26 commented
I did a merge locally and when i pushed some extra files were added for some reason. I've removed all. Please check if you still see some unwanted files.

2021-12-02 19:13 UTC, troytomasch approved these changes
I'm good to merge it. Just one more file I noticed you're missing the xss require.

2021-12-02 23:21 UTC, tejasraibagi26 commented on routes/request.js
I've added this. Also found some errors while checking it myself so fixed and updated that too.

2021-12-06 01:48 UTC, troytomasch requested changes
Left some minor comments to change

2021-12-06 01:48 UTC, troytomasch commented on public/css/user/register.css
>  #register-page {
This page needs padding on the left. Fields are pushed too far left.

2021-12-06 01:48 UTC, troytomasch commented on public/css/user/login.css
>  #login-page {
This page needs padding on the left. Fields are pushed too far left.

2021-12-06 01:48 UTC, troytomasch commented on routes/feed.js
> +  console.log(req.body);
We'll want to take this out at some point

2021-12-06 01:48 UTC, troytomasch commented on views/entry/create.handlebars
> +          required
Could we add a min and a max attribute here so users can't even enter negative numbers or numbers over 100 if they want to?

2021-12-06 01:48 UTC, troytomasch commented on public/js/register.js
> +
Can we put this inside the if(registerForm) as it gives an error on every other page as there is only an element with id gender on the register page

2021-12-06 02:39 UTC, tejasraibagi26 commented on routes/feed.js
> +  console.log(req.body);
Damn. I always miss these!

2021-12-06 02:40 UTC, tejasraibagi26 commented on views/entry/create.handlebars
> +          required
Yes we could.

2021-12-06 02:41 UTC, tejasraibagi26 commented on public/js/register.js
> +
I found the error for that. You've placed the script in main.handlebars. Rather we should just add it at the end of register.handlebars. This would also prevent unwanted loading of other js files.

I'll move the scripts in main to their respective handlebars when committing for the changes.

2021-12-06 02:45 UTC, tejasraibagi26 commented on public/css/user/register.css
>  #register-page {
Don't see this error on my machine. They are aligned perfectly in center
<img width="1440" alt="Screen Shot 2021-12-05 at 9 45 01 PM" src="https://user-images.githubusercontent.com/60872437/144778793-182aa64f-6ff5-4c83-aa3b-7f3e66c759ea.png">

2021-12-06 02:45 UTC, tejasraibagi26 commented on public/css/user/login.css
>  #login-page {
Same as the issue above

2021-12-06 02:47 UTC, tejasraibagi26 commented on public/css/user/register.css
>  #register-page {
I do see what you mean now. But I'm using flex so that'll naturally place everything in the center. So even if i add padding it won't feel right.

2021-12-06 03:57 UTC, troytomasch approved these changes

2021-12-06 03:57 UTC, merged