Updating user features
tejasraibagi26/CS546_Final_Project pull request #11
Opened 2021-12-01 03:24 UTC by troytomasch

- Added login, register, and profile page
- Added express session
- Still need to make changes to profile once other changes have been merged

2021-12-01 18:41 UTC, tejasraibagi26 requested changes
There are some small changes, other than that i feel this is good. I've seen you have added ajax script but haven't implemented it. If you could then just add it for the login in the front-end js and that should be good to go.

2021-12-01 18:41 UTC, tejasraibagi26 commented on public/js/register.js
> +
In all client validation, upon resubmit i think you should hide the error message. This is optional but will give a better understanding to the user.

2021-12-01 18:41 UTC, tejasraibagi26 commented on routes/user.js
> +    xss(inputUser.firstName),
This won't work. Prof told to wrap the individual req.body.{name}.
For eg: 
```js
let firstName = xss(req.body.firstName);
```

2021-12-01 18:41 UTC, tejasraibagi26 commented on routes/user.js
> +    res.redirect("/user/profile");
If i have understood correctly this is a route to registration. I think after successful registration the user should be redirected to /login rather than checking the user by email and redirecting to /user/profile.

2021-12-01 18:41 UTC, tejasraibagi26 commented on routes/user.js
> +  let fullName = [xss(inputName.firstName), xss(inputName.lastName)];
Wrap xss in individual req.body parameters.

2021-12-01 18:41 UTC, tejasraibagi26 commented on routes/user.js
> +    req.session.user = { id: foundUser._id };
Also save the user's first and last name as fullName in session.

2021-12-02 03:25 UTC, troytomasch commented on routes/user.js
> +    res.redirect("/user/profile");
The reason I redirected them to profile is that I essentially treat sign up as logging in as well. I don't think a user should need to login after they signup.

2021-12-02 17:19 UTC, tejasraibagi26 commented on routes/user.js
> +    res.redirect("/user/profile");
Oh okay.

2021-12-03 20:33 UTC, tejasraibagi26 approved these changes
Everything seems to be good. I'll go ahead and merge this.

2021-12-03 20:33 UTC, merged