Rgundam dev
tejasraibagi26/CS546_Final_Project pull request #19
Opened 2021-12-08 23:40 UTC by rgundam-stevens

2021-12-08 23:52 UTC, tejasraibagi26 requested changes
Just a few changes. Change them as soon as possible then I'll fix the merge conflict.

2021-12-08 23:52 UTC, tejasraibagi26 commented on data/reviews.js
>      createdAt: new Date(),
Remove this and change createdAt1 to createdAt.

2021-12-08 23:52 UTC, tejasraibagi26 commented on views/reviews/VenueReview.handlebars
> +              <p class="date">Posted on (Eastern Standard Time)     : {{this.createdAt1}}</p>
No need to mention EST.

2021-12-08 23:58 UTC, rgundam-stevens commented on data/reviews.js
>      createdAt: new Date(),
I’m using createdAt1 in my function and createdAt to display 

Because new Date() is giving date and time in 24 hour format and based on that only I’m filtering using mongo db -1 and 1

newDate().toLocaleString()is giving in form of am and pm which not able to use for filtering oldest and newest reviews

2021-12-08 23:58 UTC, rgundam-stevens commented on views/reviews/VenueReview.handlebars
> +              <p class="date">Posted on (Eastern Standard Time)     : {{this.createdAt1}}</p>
ok

2021-12-09 00:18 UTC, tejasraibagi26 approved these changes

2021-12-09 00:18 UTC, merged