Added handlebars for landing page and venue routes.
tejasraibagi26/CS546_Final_Project pull request #2
Opened 2021-11-10 21:06 UTC by tejasraibagi26

**Created handlebars for landing page and venue.**
1. Landing page has a form with textfield to input a searchTerm or simple search to fetch all venues.
2. Venue page display venue according to the searchTerm
3. Added cost filter
4. Individual venue renders specific venue with details to book slot timings

### **Landing Page**
<img width="1440" alt="Screen Shot 2021-11-10 at 4 00 31 PM" src="https://user-images.githubusercontent.com/60872437/141192837-66e94925-1298-432a-abe9-9cd8940595a6.png">

### **Search All**
<img width="1440" alt="Screen Shot 2021-11-10 at 4 00 41 PM" src="https://user-images.githubusercontent.com/60872437/141193029-11f14379-1a90-40e7-987c-1b25f8657d38.png">

### **Search Specific**
<img width="1440" alt="Screen Shot 2021-11-10 at 4 00 56 PM" src="https://user-images.githubusercontent.com/60872437/141193072-094568fe-2dc3-4340-9238-4cf4f149c5a3.png">

### **Search specific with cost filter** (check url)
<img width="1440" alt="Screen Shot 2021-11-10 at 4 01 10 PM" src="https://user-images.githubusercontent.com/60872437/141193160-97b9daa5-9095-4160-9fbe-098a4416f06a.png">

### **Individual Venue**
<img width="1440" alt="Screen Shot 2021-11-10 at 4 01 16 PM" src="https://user-images.githubusercontent.com/60872437/141193300-54b0f1c0-0bae-4519-9254-f42d370f4621.png">

2021-11-16 19:48 UTC, troytomasch requested changes

2021-11-17 00:09 UTC, tejasraibagi26 commented on backup.txt
> +<section id="search-results">
Oh my bad this wasn't supposed to be here. This is just a backup code of a file as I was testing multiple design choices.

2021-11-17 00:12 UTC, tejasraibagi26 commented on routes/request.js
> +    res.status(404).json({ err: error });
I've made these changes and also added couple more handlebars. Please check.

2021-11-24 21:25 UTC, troytomasch reviewed
Just a couple print statements I saw. Otherwise, I'm good with it

2021-11-24 21:37 UTC, tejasraibagi26 commented on data/venue.js
> +  console.log(sportToFind);
Oh look's like i forgot to remove the console logs. I'll make sure to remove all of them in my next PR. Im ahead of the current PR so can't push the changes now or most of the code will be half baked.

2021-11-24 21:38 UTC, tejasraibagi26 commented
Go ahead and merge the it.

2021-11-24 22:58 UTC, merged