Seed file, tota11y fixes and small changes
tejasraibagi26/CS546_Final_Project pull request #23
Opened 2021-12-11 22:16 UTC by tejasraibagi26

2021-12-12 20:24 UTC, troytomasch requested changes

2021-12-12 20:24 UTC, troytomasch commented on public/js/login.js
> +      console.log(data);
Remove console.log

2021-12-12 20:24 UTC, troytomasch commented on routes/feed.js
> +  console.log(activities);
Remove console.log

2021-12-12 20:24 UTC, troytomasch commented on tasks/seed.js
> +main().catch((err) => console.log(err));
Is it possible to return or something so that the file finishes running and doesn't hang at the end?

2021-12-12 20:24 UTC, troytomasch commented on tasks/seed.js
> +main().catch((err) => console.log(err));
Also, resolve conflicts

2021-12-12 20:33 UTC, troytomasch approved these changes

2021-12-12 20:33 UTC, merged

2021-12-13 00:34 UTC, tejasraibagi26 commented on tasks/seed.js
> +main().catch((err) => console.log(err));
The db wont close for some reason. I even downgraded to 3.6.9