Added routes and data for users
tejasraibagi26/CS546_Final_Project pull request #3
Opened 2021-11-11 16:28 UTC by troytomasch

- Added data for users
- Added routes for users
- Added error handling functions for user fields

2021-11-11 16:40 UTC, tejasraibagi26 requested changes

2021-11-11 16:40 UTC, tejasraibagi26 commented on data/user.js
> +  const users = await userCollection();
I think it should be 
```JavaScript
const users = await getAllUsers() 
```
else you'll be only holding the user collection in the variable.

2021-11-11 21:05 UTC, tejasraibagi26 commented on data/user.js
> +  const users = await userCollection();
And also could you add a route for login via email?

2021-11-16 19:38 UTC, troytomasch commented on data/user.js
> +  const users = await userCollection();
Made these changes

2021-11-17 00:07 UTC, tejasraibagi26 requested changes

2021-11-17 00:07 UTC, tejasraibagi26 commented on routes/user.js
> +
errorHandler for username and password missing.

2021-11-17 00:08 UTC, tejasraibagi26 commented on data/user.js
> +  const users = await userCollection();
Everything looks great, just missing errorHandlers for /login route

2021-11-17 14:05 UTC, tejasraibagi26 approved these changes
Looks good, can be merged.

2021-11-18 02:03 UTC, merged