Rgundam dev
tejasraibagi26/CS546_Final_Project pull request #8
Opened 2021-11-20 05:14 UTC by rgundam-stevens

Updated reviews.js and index.js in routes and data folders

2021-11-20 19:37 UTC, tejasraibagi26 reviewed
Please use the errorHandlers modules already available for the check. If some error handling is different create new one so others can directly use it from the file instead of redundantly typing it out.

2021-11-20 19:39 UTC, tejasraibagi26 reviewed
Please use the errorHandlers modules already available for the check. If some error handling is different create new one so others can directly use it from the file instead of redundantly typing it out.

2021-11-20 19:40 UTC, rgundam-stevens commented
I’m not so proficient in coding that’s why I’ve done so 😅

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Tejas ***@***.***>
Sent: Saturday, November 20, 2021 2:39:45 PM
To: tejasraibagi26/CS546_Final_Project ***@***.***>
Cc: Varun G ***@***.***>; Author ***@***.***>
Subject: Re: [tejasraibagi26/CS546_Final_Project] Updated reviews.js and index.js in routes and data folders (PR #8)


EXTERNAL:


@tejasraibagi26 commented on this pull request.

Please use the errorHandlers modules already available for the check. If some error handling is different create new one so others can directly use it from the file instead of redundantly typing it out.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftejasraibagi26%2FCS546_Final_Project%2Fpull%2F8%23pullrequestreview-811854376&data=04%7C01%7Crgundam%40stevens.edu%7Cf0c391c25cf34493ffc408d9ac5d81ab%7C8d1a69ec03b54345ae21dad112f5fb4f%7C0%7C0%7C637730339877282133%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LJFcwSIZ0o%2FnKeoVrP7Y7%2FHtNX5CmxNrRTiE7dz0Z9c%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWKQ4VOBSRTQF4VA2GRV4BTUM72QDANCNFSM5INRUSCQ&data=04%7C01%7Crgundam%40stevens.edu%7Cf0c391c25cf34493ffc408d9ac5d81ab%7C8d1a69ec03b54345ae21dad112f5fb4f%7C0%7C0%7C637730339877282133%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vxhPOwDKZoMmqU2YVIIGkKMWdZoQtBJdOwqiIfxbWuk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crgundam%40stevens.edu%7Cf0c391c25cf34493ffc408d9ac5d81ab%7C8d1a69ec03b54345ae21dad112f5fb4f%7C0%7C0%7C637730339877292090%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GEivItlaMsNXMQB5TopJi9QFtuzuRF7BYzM2j0YtCNA%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crgundam%40stevens.edu%7Cf0c391c25cf34493ffc408d9ac5d81ab%7C8d1a69ec03b54345ae21dad112f5fb4f%7C0%7C0%7C637730339877302044%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=EVVWCuzq5%2FrN5JP3kr%2Fgw2wuzh0CdxmXkT77jCbeGV4%3D&reserved=0>.

2021-11-20 19:49 UTC, rgundam-stevens commented
I’ll change it accordingly by tonight

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Varun G ***@***.***>
Sent: Saturday, November 20, 2021 2:40:44 PM
To: tejasraibagi26/CS546_Final_Project ***@***.***>; tejasraibagi26/CS546_Final_Project ***@***.***>
Cc: Author ***@***.***>
Subject: Re: [tejasraibagi26/CS546_Final_Project] Updated reviews.js and index.js in routes and data folders (PR #8)

I’m not so proficient in coding that’s why I’ve done so 😅

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Tejas ***@***.***>
Sent: Saturday, November 20, 2021 2:39:45 PM
To: tejasraibagi26/CS546_Final_Project ***@***.***>
Cc: Varun G ***@***.***>; Author ***@***.***>
Subject: Re: [tejasraibagi26/CS546_Final_Project] Updated reviews.js and index.js in routes and data folders (PR #8)


EXTERNAL:


@tejasraibagi26 commented on this pull request.

Please use the errorHandlers modules already available for the check. If some error handling is different create new one so others can directly use it from the file instead of redundantly typing it out.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftejasraibagi26%2FCS546_Final_Project%2Fpull%2F8%23pullrequestreview-811854376&data=04%7C01%7Crgundam%40stevens.edu%7Cf0c391c25cf34493ffc408d9ac5d81ab%7C8d1a69ec03b54345ae21dad112f5fb4f%7C0%7C0%7C637730339877282133%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=LJFcwSIZ0o%2FnKeoVrP7Y7%2FHtNX5CmxNrRTiE7dz0Z9c%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWKQ4VOBSRTQF4VA2GRV4BTUM72QDANCNFSM5INRUSCQ&data=04%7C01%7Crgundam%40stevens.edu%7Cf0c391c25cf34493ffc408d9ac5d81ab%7C8d1a69ec03b54345ae21dad112f5fb4f%7C0%7C0%7C637730339877282133%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vxhPOwDKZoMmqU2YVIIGkKMWdZoQtBJdOwqiIfxbWuk%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crgundam%40stevens.edu%7Cf0c391c25cf34493ffc408d9ac5d81ab%7C8d1a69ec03b54345ae21dad112f5fb4f%7C0%7C0%7C637730339877292090%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=GEivItlaMsNXMQB5TopJi9QFtuzuRF7BYzM2j0YtCNA%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Crgundam%40stevens.edu%7Cf0c391c25cf34493ffc408d9ac5d81ab%7C8d1a69ec03b54345ae21dad112f5fb4f%7C0%7C0%7C637730339877302044%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=EVVWCuzq5%2FrN5JP3kr%2Fgw2wuzh0CdxmXkT77jCbeGV4%3D&reserved=0>.

2021-11-24 15:56 UTC, tejasraibagi26 requested changes
Please go through the changes.

2021-11-24 15:56 UTC, tejasraibagi26 commented on data/reviews.js
> +    _id: ObjectId(),
You don't have to create _id, mongodb does it for you automatically.

2021-11-24 15:56 UTC, tejasraibagi26 commented on data/reviews.js
> +      flag3 = "true";
Don't store boolean as string.

2021-11-24 15:56 UTC, tejasraibagi26 commented on data/reviews.js
> +  if (flag3 != "true") {
Kindly change all string value to respective boolean values.

2021-11-24 15:56 UTC, tejasraibagi26 commented on data/reviews.js
> +  let flag1, flag2, flag3, flag4;
Atleast give a comment what individual flag does. This is very confusing.

2021-11-24 15:56 UTC, tejasraibagi26 commented on routes/reviews.js
> +        const updatedReview = await resData.updateReviewText(req.params.id, req.params.userId, req.params.venueId, resInfo.reviewText);
You have extracted all data in their respective variables, so use that instead. Also destructure resInfo as we need to wrap individual params with xss.

2021-11-24 15:56 UTC, tejasraibagi26 commented on routes/reviews.js
> +        const updatedReview = await resData.updateReviewRating(req.params.id, req.params.userId, req.params.venueId, resInfo.rating);
Follow the same as above.

2021-11-24 15:56 UTC, tejasraibagi26 commented on routes/reviews.js
> +        await resData.removeReview(req.params.id, req.params.userId, req.params.venueId);
Same as above. Never use req as param input always use the respective variable.

2021-11-24 15:56 UTC, tejasraibagi26 commented on routes/reviews.js
> +        const postReview = await resData.addReview(req.params.userId, req.params.venueId, resInfo.reviewText, resInfo.rating);
Same as above.

2021-11-24 15:56 UTC, tejasraibagi26 commented on routes/reviews.js
> +        const updatedReview = await resData.upVote(req.params.reviewId, req.params.userId);
Same as above.

2021-11-24 15:56 UTC, tejasraibagi26 commented on routes/reviews.js
> +        const updatedReview = await resData.downVote(req.params.reviewId, req.params.userId);
Same as above.

2021-11-24 15:56 UTC, tejasraibagi26 commented on routes/reviews.js
> +        const updatedReview = await resData.removeUpvote(req.params.reviewId, req.params.userId);
Same as above.

2021-11-24 15:56 UTC, tejasraibagi26 commented on routes/reviews.js
> +        const updatedReview = await resData.removeDownvote(req.params.reviewId, req.params.userId);
Same as above.

2021-11-24 15:58 UTC, tejasraibagi26 commented on data/reviews.js
> +    _id: ObjectId(),
Unless it's a sub-doc this is fine.

2021-11-25 19:44 UTC, tejasraibagi26 approved these changes
Everything seems good. I'll wait for Troy to review it and then he can merge it with main.

2021-11-25 19:46 UTC, rgundam-stevens commented
Sure ..! Thanks Tejas

2021-11-29 21:21 UTC, troytomasch requested changes
I've made some comments that would be nice if you could fix them. A few of the changes are just making sure you do the error checking before you use the inputs. And also you do a lot of checking of the ObjectId when you could use the function from the error handler. Plus there's some other comments. Just take a look when you get a chance.

2021-11-29 21:21 UTC, troytomasch commented on data/reviews.js
> +  const review = await this.getReviewById(id);
There is no need for this as it is not used anywhere

2021-11-29 21:21 UTC, troytomasch commented on data/reviews.js
> +  errorHandler.checkIfValidRating(rating);
Move this up again

2021-11-29 21:21 UTC, troytomasch commented on data/reviews.js
> +  const review = await this.getReviewById(id);
Can remove, this is not used anywhere

2021-11-29 21:21 UTC, troytomasch commented on routes/reviews.js
> +    let array = [userId, venueId];
This variable is not used

2021-12-02 01:00 UTC, troytomasch approved these changes

2021-12-02 02:19 UTC, merged